name: Sync addon metadata translations

on:
  push:
    branches: [ Matrix, Nexus ]
    paths:
      - '**addon.xml'
      - '**resource.language.**strings.po'

jobs:
  default:
    if: github.repository == 'kodi-game/game.libretro'
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: project

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+https://github.com/xbmc/sync_addon_metadata_translations.git

      - name: Run sync-addon-metadata-translations
        run: |
          sync-addon-metadata-translations
        working-directory: ./project

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Sync of addon metadata translations" -a
        working-directory: ./project
        continue-on-error: true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          directory: ./project